import { response } from "express"
import Chat from "../models/Chat.js"
import User from "../models/User.js"
import imagekit from "../configs/imagekit.js"
import openai from "../configs/openai.js"
import axios from 'axios'


//text based ai chat message controller
export const textMessagecontroller = async(req,res)=>{
  try {
    const userId = req.user._id
    //check credits
    if(req.user.credits < 1 ){
      return res.json({success: false, message:"You don't have enough credits to use this feature "})
    }
    const {chatId,prompt}=req.body

    const chat = await Chat.findOne({userId,_id:chatId})
    chat.messages.push({role:"user",content:prompt,timestamp:Date.now(),isImage:false})
const {choices} = await openai.chat.completions.create({
    model: "gemini-3-flash-preview",
    messages: [
       
        {
            role: "user",
            content: prompt,
        },
    ],
});
  const reply = {...choices[0].message,timestamp:Date.now(),isImage:false}
  res.json({success:true,reply})
  chat.messages.push(reply)
  await  chat.save()

  await User.updateOne({_id:userId},{$inc:{credits:-1}})

  
  } catch (error) {
    res.json({success:false,message:error.message})
    
  }

}

///image generarion message controller

export const ImageMessageController = async(req,res)=>{
  try {
    
    const userId = req.user._id
    //check credits
    if(req.user.credits < 2 ){
      return res.json({success: false, message:"You don't have enough credits to use this feature "})
    }
    const {prompt,chatId,isPublished} = req.body
    //find chat 
    const chat = await Chat.findOne({userId,_id:chatId})

    //push user message
    chat.messages.push({role:"user",content:prompt,timestamp:Date.now(),isImage:false})

    //encode the prompt 
    const encodedPrompt = encodeURIComponent(prompt)

    //construch imagekit ai generator url
    const generatedImageUrl = `${process.env.IMAGELKIT_URLENDPOINT}/
    ik-genimg-prompt-${encodedPrompt}/quickjgpt/${Date.now()}.png?tr=w-800,h-800` 
      //trigger generated by image kit

     const aiImageResponce = await axios.get(generatedImageUrl,{responseType:'arraybuffer'})

     //convert to base64
     
     const base64Image = `data:image/png;base64,${Buffer.from(aiImageResponce.data,"binary").toString('base64')}`
  
     //upload to imagekit media library
     const uploadresponse = await imagekit.upload({
      file:base64Image,
      fileName:`${Date.now()}.png`,
      folder:"quickgpt"
     })


    const reply = {
      role:"assistant",
      content:uploadresponse.url,
      timestamp:Date.now(),
      isImage:true,
      isPublished
  }
    res.json({success:true,reply})
    chat.messages.push(reply)
    await chat.save()

      await User.updateOne({_id:userId},{$inc:{credits:-2}})

  
    }
    catch (error) {
    res.json({success:false,message:error.message})
  }
}

